###
GET localhost:8080/awsTest/sqs-pub
Content-Type: application/json
Accept: */*

###
GET localhost:8080/awsTest/sns-pub
Content-Type: application/json
Accept: */*

###
GET localhost:8080/awsTest/sqs-sub
Content-Type: application/json
Accept: */*



